"".add STEXT nosplit size=20 args=0x10 locals=0x0
	0x0000 00000 (direct_topfunc_call.go:3)	TEXT	"".add(SB), NOSPLIT|ABIInternal, $0-16
	0x0000 00000 (direct_topfunc_call.go:3)	FUNCDATA	$0, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0000 00000 (direct_topfunc_call.go:3)	FUNCDATA	$1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0000 00000 (direct_topfunc_call.go:3)	MOVL	"".b+12(SP), AX
	0x0004 00004 (direct_topfunc_call.go:3)	MOVL	"".a+8(SP), CX
	0x0008 00008 (direct_topfunc_call.go:3)	ADDL	CX, AX
	0x000a 00010 (direct_topfunc_call.go:3)	MOVL	AX, "".~r2+16(SP)
	0x000e 00014 (direct_topfunc_call.go:3)	MOVB	$1, "".~r3+20(SP)
	0x0013 00019 (direct_topfunc_call.go:3)	RET
	0x0000 8b 44 24 0c 8b 4c 24 08 01 c8 89 44 24 10 c6 44  .D$..L$....D$..D
	0x0010 24 14 01 c3                                      $...
"".main STEXT nosplit size=1 args=0x0 locals=0x0
	0x0000 00000 (direct_topfunc_call.go:5)	TEXT	"".main(SB), NOSPLIT|ABIInternal, $0-0
	0x0000 00000 (direct_topfunc_call.go:5)	FUNCDATA	$0, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0000 00000 (direct_topfunc_call.go:5)	FUNCDATA	$1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0000 00000 (direct_topfunc_call.go:5)	RET
	0x0000 c3                                               .
go.cuinfo.packagename. SDWARFINFO dupok size=0
	0x0000 6d 61 69 6e                                      main
go.info."".add$abstract SDWARFINFO dupok size=25
	0x0000 04 2e 61 64 64 00 01 01 11 61 00 00 00 00 00 00  ..add....a......
	0x0010 11 62 00 00 00 00 00 00 00                       .b.......
	rel 0+0 t=24 type.bool+0
	rel 0+0 t=24 type.int32+0
	rel 12+4 t=29 go.info.int32+0
	rel 20+4 t=29 go.info.int32+0
""..inittask SNOPTRDATA size=24
	0x0000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 00 00 00 00 00 00 00 00                          ........
gclocals·33cdeccccebe80329f1fdbee7f5874cb SRODATA dupok size=8
	0x0000 01 00 00 00 00 00 00 00                          ........
