[monitorunit]
  notifylist = ["xiaohong","xiaoli","xiaowang"]
  value = [5,6,7]
  default = false

[ap]
  notifylist = ["xiaohong","xiaoli","xiaowang"]
  value = [5,6,7]
  default = false


[pc1]
  notifylist = ["xiaohong","xiaoli","xiaowang"]
  value = [5,6,7]
  default = false


[pc2]
  notifylist = ["xiaohong","xiaoli","xiaowang"]
  value = [5,6,7]
  default = false

[c1]
  notifylist = ["xiaohong","xiaoli","xiaowang"]
  value = [5,6,7]
  default = false

[c2]
  notifylist = ["xiaohong","xiaoli","xiaowang"]
  value = [5,6,7]
  default = false