[miner]
  hostnames = ["miners"]
  value = [5]
  default = -1
[ap]
  hostnames = ["xiaohong","xiaoli","xiaowang"]
  value = [5,6,7]
  default = -1


[pc1]
  hostnames = ["xiaohong","xiaoli","xiaowang"]
  value = [5,6,7]
  default = -1


[pc2]
  hostnames = ["xiaohong","xiaoli","xiaowang"]
  value = [5,6,7]
  default = -1

[c1]
  hostnames = ["xiaohong","xiaoli","xiaowang"]
  value = [5,6,7]
  default = -1

[c2]
  hostnames = ["xiaohong","xiaoli","xiaowang"]
  value = [5,6,7]
  default = -1